import Providers from "@/providers";
import { SearchProvider } from "@/contexts/SearchContext";
import Header from "@/components/layout/Header";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SearchProvider>
            <div className="min-h-screen flex flex-col">
              <Header />

              {/* Main Content */}
              <main className="flex-1 container mx-auto p-8 grid grid-cols-12 gap-6">
                {/* Left Column */}
                <div className="col-span-3 bg-gray-100 p-4 rounded-lg">
                  Left Column
                </div>

                {/* Center Column */}
                <div className="col-span-6 bg-white p-4 rounded-lg shadow">
                  {children}
                </div>

                {/* Right Column */}
                <div className="col-span-3 bg-gray-100 p-4 rounded-lg">
                  Right Column
                </div>
              </main>
            </div>
          </SearchProvider>
        </Providers>
      </body>
    </html>
  );
}
